# Generated by Django 4.2.18 on 2025-04-29 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_projects', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customer_projects.project'),
        ),
        migrations.AddField(
            model_name='generalnotifier',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='generalnotifier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attending_events', to='core.employee'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='core.employee'),
        ),
        migrations.AddField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_events', to='core.customer'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtracker',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emailmessage'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emailaccount'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailmessage'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='related_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='related_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lead'),
        ),
        migrations.AddField(
            model_name='emailfoldermessage',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emailfolder'),
        ),
        migrations.AddField(
            model_name='emailfoldermessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emailmessage'),
        ),
        migrations.AddField(
            model_name='emailfolder',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emailaccount'),
        ),
        migrations.AddField(
            model_name='emailfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.emailfolder'),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.emailmessage'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_account', to='core.employee'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailprovider'),
        ),
        migrations.AddField(
            model_name='customer',
            name='assigned_to',
            field=models.ForeignKey(help_text='Employee responsible for this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='core.employee'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='participants',
            field=models.ManyToManyField(related_name='chat_sessions', to='core.employee'),
        ),
        migrations.AddField(
            model_name='chatnotification',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to='core.employee'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='core.employee'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.employee'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', 'transaction_date'], name='core_transa_custome_3e73e8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['invoice', 'transaction_date'], name='core_transa_invoice_9c2317_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'transaction_date'], name='core_transa_status_c27c37_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesubscription',
            index=models.Index(fields=['customer', 'service', 'status'], name='core_servic_custome_819c22_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesubscription',
            index=models.Index(fields=['start_date', 'end_date'], name='core_servic_start_d_34902d_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerule',
            index=models.Index(fields=['user', 'is_active'], name='core_schedu_user_id_362165_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerule',
            index=models.Index(fields=['recurrence_type', 'day_of_week'], name='core_schedu_recurre_c5b06f_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerule',
            index=models.Index(fields=['start_time', 'end_time'], name='core_schedu_start_t_4471f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedulerule',
            constraint=models.CheckConstraint(check=models.Q(('max_booking_duration__gt', models.F('min_booking_duration'))), name='max_duration_greater_than_min'),
        ),
        migrations.AddConstraint(
            model_name='schedulerule',
            constraint=models.CheckConstraint(check=models.Q(('day_of_month__gte', 1), ('day_of_month__lte', 31)), name='valid_day_of_month'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'transaction_date'], name='core_paymen_custome_f31f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'transaction_date'], name='core_paymen_invoice_e68841_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'transaction_date'], name='core_paymen_status_ea6098_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['start_time', 'end_time'], name='core_meetin_start_t_eea725_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_type', 'status'], name='core_meetin_meeting_2acbed_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organizer'], name='core_meetin_organiz_78ec23_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'priority'], name='core_lead_status_4fab71_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='core_lead_assigne_30d8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='core_lead_email_40e23f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='core_lead_created_054771_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaccess',
            index=models.Index(fields=['ip_address', 'access_time'], name='core_ipacce_ip_addr_f15b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaccess',
            index=models.Index(fields=['user', 'access_time'], name='core_ipacce_user_id_37a54d_idx'),
        ),
        migrations.AddIndex(
            model_name='generalnotifier',
            index=models.Index(fields=['user', 'is_read'], name='core_genera_user_id_0f2374_idx'),
        ),
        migrations.AddIndex(
            model_name='generalnotifier',
            index=models.Index(fields=['notification_type'], name='core_genera_notific_f6a7db_idx'),
        ),
        migrations.AddIndex(
            model_name='generalnotifier',
            index=models.Index(fields=['event_datetime'], name='core_genera_event_d_e3e329_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time', 'end_time'], name='core_event_start_t_0aa7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'status'], name='core_event_event_t_5dba9e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', 'is_recurring'], name='core_event_created_263a72_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='core_employ_employe_29089f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'position'], name='core_employ_departm_7bf91b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active', 'created_at'], name='core_employ_is_acti_b4daaa_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['message_type', 'status'], name='core_emailm_message_46ee62_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['account', 'created_at'], name='core_emailm_account_281e06_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['thread_id'], name='core_emailm_thread__698083_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailfoldermessage',
            unique_together={('folder', 'message')},
        ),
        migrations.AlterUniqueTogether(
            name='emailfolder',
            unique_together={('account', 'name', 'parent')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company_name'], name='core_custom_company_fdbc87_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='core_custom_email_899d12_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status', 'assigned_to'], name='core_custom_status_77014c_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='core_custom_created_629a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['recipient', 'is_seen'], name='core_chatno_recipie_d8a80a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatnotification',
            index=models.Index(fields=['created_at'], name='core_chatno_created_fb97c8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='core_chatme_session_36fde0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'timestamp'], name='core_chatme_sender__111450_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_read', 'timestamp'], name='core_chatme_is_read_c1eab7_idx'),
        ),
    ]
