# Generated by Django 4.2.18 on 2025-02-04 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invoice_balance_due_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance_due',
        ),
    ]
