# Generated by Django 4.2.18 on 2025-03-06 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_lead_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralNotifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('meeting', 'Meeting'), ('task', 'Task'), ('project', 'Project'), ('event', 'Event'), ('document', 'Document'), ('video_conference', 'Video Conference'), ('deadline', 'Deadline'), ('reminder', 'Reminder'), ('other', 'Other')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_datetime', models.DateTimeField(help_text='When the event is happening or due')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_datetime', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_genera_user_id_0f2374_idx'), models.Index(fields=['notification_type'], name='core_genera_notific_f6a7db_idx'), models.Index(fields=['event_datetime'], name='core_genera_event_d_e3e329_idx')],
            },
        ),
    ]
