# Generated by Django 4.2.18 on 2025-02-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invoice_last_payment_date_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date'], 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', 'transaction_date'], name='core_transa_custome_3e73e8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['invoice', 'transaction_date'], name='core_transa_invoice_9c2317_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'transaction_date'], name='core_transa_status_c27c37_idx'),
        ),
    ]
