# Generated by Django 4.2.18 on 2025-02-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='reference_number',
            new_name='reference',
        ),
    ]
