# Generated by Django 4.2.18 on 2025-03-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_generalnotifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalnotifier',
            name='reference_id',
            field=models.IntegerField(blank=True, help_text='ID of the referenced object (meeting, task, event)', null=True),
        ),
    ]
