# Generated by Django 4.2.18 on 2025-03-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_generalnotifier_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalnotifier',
            name='notification_type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('task', 'Task'), ('project', 'Project'), ('event', 'Event'), ('document', 'Document'), ('video_conference', 'Video Conference'), ('deadline', 'Deadline'), ('chat', 'Chat Message'), ('reminder', 'Reminder'), ('other', 'Other')], max_length=20),
        ),
    ]
