# Generated by Django 4.2.18 on 2025-02-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailaccount_emailfolder_emailmessage_emailtracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='requires_auth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='uses_tls',
            field=models.BooleanField(default=True),
        ),
    ]
