# Generated by Django 4.2.18 on 2025-02-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_reference_number_payment_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-transaction_date'], 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'transaction_date'], name='core_paymen_custome_f31f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'transaction_date'], name='core_paymen_invoice_e68841_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'transaction_date'], name='core_paymen_status_ea6098_idx'),
        ),
    ]
