# Generated by Django 4.2.18 on 2025-02-15 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailaccount_requires_auth_emailaccount_uses_tls'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField()),
                ('imap_server', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField()),
                ('requires_auth', models.BooleanField(default=True)),
                ('uses_tls', models.BooleanField(default=True)),
                ('domain', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='imap_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='imap_server',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='smtp_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='smtp_server',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.emailprovider'),
        ),
    ]
