# Generated by Django 4.2.18 on 2025-03-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_generalnotifier_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalDocument',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicyAcceptance',
        ),
    ]
