# Generated by Django 4.2.18 on 2025-02-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesubscription',
            options={'ordering': ['-start_date'], 'verbose_name': 'Service Subscription', 'verbose_name_plural': 'Service Subscriptions'},
        ),
        migrations.AddIndex(
            model_name='servicesubscription',
            index=models.Index(fields=['customer', 'service', 'status'], name='core_servic_custome_819c22_idx'),
        ),
        migrations.AddIndex(
            model_name='servicesubscription',
            index=models.Index(fields=['start_date', 'end_date'], name='core_servic_start_d_34902d_idx'),
        ),
    ]
