# Generated by Django 4.2.18 on 2025-03-12 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_legaldocument_delete_privacypolicyacceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '(999)999-9999'", regex='^\\(\\d{3}\\)\\d{3}-\\d{4}$')]),
        ),
    ]
