# Generated by Django 4.2.18 on 2025-02-19 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailprovider_alter_emailaccount_imap_port_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Primary contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '(999)999-9999'", regex='^\\(\\d{3}\\)\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '(999)999-9999'", regex='^\\(\\d{3}\\)\\d{3}-\\d{4}$')]),
        ),
    ]
