# Generated by Django 4.2.18 on 2025-02-09 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('path', models.CharField(max_length=255)),
                ('access_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('is_ajax', models.BooleanField(default=False)),
                ('is_secure', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-access_time'],
                'indexes': [models.Index(fields=['ip_address', 'access_time'], name='core_ipacce_ip_addr_f15b4c_idx'), models.Index(fields=['user', 'access_time'], name='core_ipacce_user_id_37a54d_idx')],
            },
        ),
    ]
