# Generated by Django 4.2.18 on 2025-02-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customer_options_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Employee profile picture', null=True, upload_to='employee_photos/'),
        ),
    ]
