# Generated by Django 4.2.18 on 2025-04-08 01:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_projects', '0003_alter_project_options_remove_project_actual_cost_and_more'),
        ('core', '0007_alter_lead_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('project_code', models.CharField(blank=True, max_length=50)),
                ('task_description', models.CharField(blank=True, max_length=200)),
                ('product_or_service', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='core_invoic_custome_0c3eac_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='core_invoic_invoice_aef6bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='core_invoic_due_dat_5f47fd_idx',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='amount_due',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='services',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customer_projects.project'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.invoice'),
        ),
    ]
