# Generated by Django 4.2.18 on 2025-02-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_employee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='carrier',
            field=models.CharField(blank=True, choices=[('rogers', 'Rogers'), ('bell', 'Bell Canada'), ('public', 'Public Mobile'), ('telus', 'Telus'), ('btc', 'Batelco'), ('aliv', 'Aliv - Bahamas'), ('metro', 'Metro PCS'), ('virgin', 'Virgin Mobile')], help_text='Mobile carrier for SMS notifications', max_length=20),
        ),
    ]
