# Generated by Django 4.2.18 on 2025-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_invoicelineitem_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('zoom', 'Zoom Meeting'), ('in_person', 'In Person'), ('phone', 'Phone Call'), ('teams', 'Microsoft Teams'), ('google_import', 'Google Calendar Import'), ('other', 'Other')], help_text='Type of meeting', max_length=20),
        ),
    ]
