# Generated by Django 4.2.18 on 2025-04-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_meeting_google_event_id_alter_meeting_meeting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_known_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_known_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
