# Generated by Django 4.2.18 on 2025-04-17 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_employee_last_known_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='ZIP/Postal code must be in the format: 12345, 12345-6789, or M3J 1L1', regex='^(\\d{5}(-\\d{4})?|[A-Za-z]\\d[A-Za-z]\\s?\\d[A-Za-z]\\d)$')]),
        ),
    ]
