# Generated by Django 4.2.18 on 2025-02-10 06:19

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_schedulerule_scheduleexception'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_customer_details', 'Can view customer details'), ('can_edit_customer', 'Can edit customer information'), ('can_assign_customer', 'Can assign customer to employee')]},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_employee_details', 'Can view employee details'), ('can_edit_employee_details', 'Can edit employee details'), ('can_terminate_employee', 'Can terminate employee')]},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time'], 'permissions': [('can_manage_events', 'Can manage events'), ('can_view_all_events', 'Can view all events')]},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'permissions': [('can_convert_lead', 'Can convert lead to customer'), ('can_assign_lead', 'Can assign lead to employee')]},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-start_time'], 'permissions': [('can_schedule_meetings', 'Can schedule meetings'), ('can_cancel_meetings', 'Can cancel meetings')]},
        ),
        migrations.AlterModelOptions(
            name='schedulerule',
            options={'ordering': ['recurrence_type', 'start_time']},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='core_event_custome_3e6554_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='core_event_created_e1ef17_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, help_text='Date of last contact with customer', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, help_text='Employee termination date', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end',
            field=models.DateTimeField(blank=True, help_text='When the recurrence ends', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_minutes',
            field=models.IntegerField(default=15, help_text='Minutes before event to send reminder'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='conversion_date',
            field=models.DateTimeField(blank=True, help_text='When was the lead converted to a customer?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_to_customer',
            field=models.ForeignKey(blank=True, help_text='Customer record if lead was converted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_lead', to='core.customer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value of the lead', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contacted',
            field=models.DateTimeField(blank=True, help_text='When was the lead last contacted?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Lead priority level', max_length=10),
        ),
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, help_text='Physical meeting location if applicable', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='schedulerule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(help_text='Street address', validators=[django.core.validators.RegexValidator(message='Address can only contain letters, numbers, spaces, and basic punctuation', regex="^[\\w\\s\\-\\',./\\\\#]+$")]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='assigned_to',
            field=models.ForeignKey(help_text='Employee responsible for this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='City name can only contain letters, spaces, and hyphens', regex='^[a-zA-Z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(help_text='Official company name', max_length=200, validators=[django.core.validators.RegexValidator(message='Company name can only contain letters, numbers, spaces, and basic punctuation', regex="^[\\w\\s\\-\\',.&]+$")]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(help_text="Primary contact person's name", max_length=100, validators=[django.core.validators.RegexValidator(message='Contact person name can only contain letters, spaces, and hyphens', regex="^[\\w\\s\\-\\']+$")]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text='Primary contact email', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Primary contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='State name can only contain letters, spaces, and hyphens', regex='^[a-zA-Z\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL', null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='ZIP code must be in the format: 12345 or 12345-6789', regex='^\\d{5}(-\\d{4})?$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='carrier',
            field=models.CharField(blank=True, choices=[('att', 'AT&T'), ('tmobile', 'T-Mobile'), ('verizon', 'Verizon'), ('sprint', 'Sprint'), ('boost', 'Boost Mobile'), ('cricket', 'Cricket'), ('metro', 'Metro PCS'), ('virgin', 'Virgin Mobile')], help_text='Mobile carrier for SMS notifications', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('general', 'General'), ('sales', 'Sales'), ('support', 'Support'), ('engineering', 'Engineering'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('hr', 'Human Resources')], default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(4, 'Employee ID must be at least 4 characters'), django.core.validators.RegexValidator(message='Employee ID can only contain letters, numbers, and hyphens', regex='^[A-Za-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Employee hire date', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this employee is currently active'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('junior', 'Junior'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Employee profile picture', null=True, upload_to=core.models.Employee.profile_picture_path),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#3788d8', help_text='Event color in calendar', max_length=7),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Event description', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(help_text='Event end time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('task', 'Task'), ('call', 'Phone Call'), ('reminder', 'Reminder'), ('appointment', 'Appointment'), ('custom', 'Custom Event')], default='custom', help_text='Type of event', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this event repeats'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, help_text='Event location', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence_rule',
            field=models.CharField(blank=True, help_text='iCal RRULE format for recurring events', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(help_text='Event start time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Event title', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(help_text='Employee responsible for this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_name',
            field=models.CharField(help_text='Company name', max_length=200, validators=[django.core.validators.RegexValidator(message='Company name can only contain letters, numbers, spaces, and basic punctuation', regex="^[\\w\\s\\-\\',.&]+$")]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_person',
            field=models.CharField(help_text='Primary contact person', max_length=100, validators=[django.core.validators.RegexValidator(message='Contact person name can only contain letters, spaces, and hyphens', regex="^[\\w\\s\\-\\']+$")]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(help_text='Primary contact email', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(help_text='Primary contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('social', 'Social Media'), ('email', 'Email Campaign'), ('trade_show', 'Trade Show'), ('cold_call', 'Cold Call'), ('other', 'Other')], help_text='Where did this lead come from?', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('negotiating', 'Negotiating'), ('converted', 'Converted'), ('lost', 'Lost')], db_index=True, default='new', help_text='Current status of the lead', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attending_meetings', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='customer_meetings', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True, help_text='Meeting description and agenda'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(help_text='Meeting end time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='lead_meetings', to='core.lead'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('zoom', 'Zoom Meeting'), ('in_person', 'In Person'), ('phone', 'Phone Call'), ('teams', 'Microsoft Teams'), ('other', 'Other')], help_text='Type of meeting', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(help_text='Meeting start time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(help_text='Meeting title', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='buffer_after',
            field=models.IntegerField(default=15, help_text='Required buffer time after bookings (minutes)'),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='buffer_before',
            field=models.IntegerField(default=15, help_text='Required buffer time before bookings (minutes)'),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='day_of_month',
            field=models.IntegerField(blank=True, help_text='Day of month (1-31) for monthly/yearly recurrence', null=True),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Specific day for weekly recurrence', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='end_time',
            field=models.TimeField(help_text='Daily end time for availability'),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this rule is currently active'),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='max_booking_duration',
            field=models.IntegerField(default=240, help_text='Maximum booking duration in minutes'),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='max_bookings_per_day',
            field=models.IntegerField(default=5, help_text='Maximum number of bookings allowed per day'),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='min_booking_duration',
            field=models.IntegerField(default=30, help_text='Minimum booking duration in minutes'),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Month for yearly recurrence', null=True),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='name',
            field=models.CharField(help_text='Name of the scheduling rule', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='recurrence_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='How often this rule repeats', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='start_time',
            field=models.TimeField(help_text='Daily start time for availability'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company_name'], name='core_custom_company_fdbc87_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='core_custom_email_899d12_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['status', 'assigned_to'], name='core_custom_status_77014c_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='core_custom_created_629a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='core_employ_employe_29089f_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'position'], name='core_employ_departm_7bf91b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active', 'created_at'], name='core_employ_is_acti_b4daaa_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'status'], name='core_event_event_t_5dba9e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', 'is_recurring'], name='core_event_created_263a72_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'priority'], name='core_lead_status_4fab71_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='core_lead_assigne_30d8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='core_lead_email_40e23f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='core_lead_created_054771_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['start_time', 'end_time'], name='core_meetin_start_t_eea725_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_type', 'status'], name='core_meetin_meeting_2acbed_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organizer'], name='core_meetin_organiz_78ec23_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerule',
            index=models.Index(fields=['user', 'is_active'], name='core_schedu_user_id_362165_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerule',
            index=models.Index(fields=['recurrence_type', 'day_of_week'], name='core_schedu_recurre_c5b06f_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerule',
            index=models.Index(fields=['start_time', 'end_time'], name='core_schedu_start_t_4471f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedulerule',
            constraint=models.CheckConstraint(check=models.Q(('max_booking_duration__gt', models.F('min_booking_duration'))), name='max_duration_greater_than_min'),
        ),
        migrations.AddConstraint(
            model_name='schedulerule',
            constraint=models.CheckConstraint(check=models.Q(('day_of_month__gte', 1), ('day_of_month__lte', 31)), name='valid_day_of_month'),
        ),
    ]
