# Generated by Django 4.2.18 on 2025-04-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='is_invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
