# Generated by Django 4.2.18 on 2025-02-17 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_projects', '0002_projectreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectreport',
            name='file',
        ),
        migrations.AddField(
            model_name='projectreport',
            name='attachments',
            field=models.FileField(blank=True, help_text='Supporting documents', null=True, upload_to='project_reports/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='projectreport',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, help_text='Report content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectreport',
            name='report_type',
            field=models.CharField(choices=[('progress', 'Progress Report'), ('status', 'Status Update'), ('financial', 'Financial Report'), ('risk', 'Risk Assessment'), ('milestone', 'Milestone Report'), ('technical', 'Technical Report'), ('other', 'Other')], default='Progress Report', help_text='Type of report', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
