# Generated by Django 4.2.18 on 2025-02-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_projects', '0003_remove_projectreport_file_projectreport_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
