# Generated by Django 4.2.18 on 2025-02-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_projects', '0004_alter_project_name_alter_project_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planning', max_length=20),
        ),
    ]
