# Generated by Django 4.2.18 on 2025-02-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_projects', '0005_projectphase_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectphase',
            options={},
        ),
    ]
