# Generated by Django 4.2.18 on 2025-04-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='download_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='download_user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
