# Generated by Django 4.2.18 on 2025-04-22 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('proposal', 'Proposal'), ('report', 'Report'), ('letter', 'Letter'), ('invoice', 'Invoice'), ('memo', 'Memo'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('content', models.JSONField(blank=True, null=True)),
                ('plain_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('is_template', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('is_latest_version', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_documents', to='core.employee')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.customer')),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to='document_editor.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to='core.employee')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, null=True)),
                ('category', models.CharField(choices=[('contract', 'Contracts'), ('proposal', 'Proposals'), ('report', 'Reports'), ('letter', 'Letters'), ('invoice', 'Invoices'), ('form', 'Forms'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to='core.employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the editing session started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the editing session ended', null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of last activity in this session')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is currently active')),
                ('client_info', models.CharField(blank=True, help_text='Client information (browser, IP, etc.)', max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sessions', to='document_editor.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selection_start', models.JSONField(blank=True, null=True)),
                ('selection_end', models.JSONField(blank=True, null=True)),
                ('selected_text', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_comments', to='core.employee')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='document_editor.document')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='document_editor.documentcomment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to='core.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('comment', 'Can Comment'), ('edit', 'Can Edit'), ('manage', 'Can Manage')], default='view', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_collaborators', to='core.employee')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='document_editor.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_collaborations', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to='core.employee')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='document_editor.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('department_required', models.CharField(blank=True, choices=[('general', 'General'), ('sales', 'Sales'), ('support', 'Support'), ('engineering', 'Engineering'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('hr', 'Human Resources')], max_length=100)),
                ('position_required', models.CharField(blank=True, choices=[('unassigned', 'Unassigned'), ('junior', 'Junior'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='core.employee')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='document_editor.documentapprovalworkflow')),
            ],
            options={
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DocumentApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.employee')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='document_editor.documentapprovalstep')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='document_editor.documentapprovalworkflow')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_document_versions', to='core.employee')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='document_editor.document')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('variable_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/No'), ('currency', 'Currency'), ('customer', 'Customer Field'), ('project', 'Project Field'), ('employee', 'Employee Field')], max_length=20)),
                ('field_mapping', models.CharField(blank=True, help_text='Field name in the related model', max_length=100)),
                ('default_value', models.CharField(blank=True, help_text='Default value if no value is provided', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the variable for users')),
                ('required', models.BooleanField(default=False)),
                ('date_format', models.CharField(blank=True, help_text="Format string for date variables (e.g., '%Y-%m-%d')", max_length=50)),
                ('number_format', models.CharField(blank=True, help_text="Format string for number variables (e.g., '{:.2f}')", max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='document_editor.documenttemplate')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('template', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['category'], name='document_ed_categor_f9ffc6_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['is_public'], name='document_ed_is_publ_a417a1_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['created_by'], name='document_ed_created_cf7e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='documenteditsession',
            index=models.Index(fields=['document', 'is_active'], name='document_ed_documen_1f9bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='documenteditsession',
            index=models.Index(fields=['user', 'is_active'], name='document_ed_user_id_f887e9_idx'),
        ),
        migrations.AddIndex(
            model_name='documenteditsession',
            index=models.Index(fields=['last_activity'], name='document_ed_last_ac_84e048_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['document'], name='document_ed_documen_991876_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['author'], name='document_ed_author__cb6b61_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['is_resolved'], name='document_ed_is_reso_587d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollaborator',
            index=models.Index(fields=['document'], name='document_ed_documen_f08952_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollaborator',
            index=models.Index(fields=['employee'], name='document_ed_employe_7e1e20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentcollaborator',
            unique_together={('document', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='documentapprovalstep',
            unique_together={('workflow', 'order')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['author'], name='document_ed_author__30078a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='document_ed_documen_13f844_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='document_ed_status_4fc471_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_template'], name='document_ed_is_temp_d43c34_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_latest_version'], name='document_ed_is_late_cf7892_idx'),
        ),
    ]
