# Generated by Django 4.2.18 on 2025-03-02 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lead_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When the editing session started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When the editing session ended', null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of last activity in this session')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is currently active')),
                ('client_info', models.CharField(blank=True, help_text='Client information (browser, IP, etc.)', max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='documentcollaborator',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='document_ed_title_18a9a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='document_ed_created_eec8c6_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_documents', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('contract', 'Contract'), ('proposal', 'Proposal'), ('report', 'Report'), ('letter', 'Letter'), ('invoice', 'Invoice'), ('memo', 'Memo'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='plain_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='category',
            field=models.CharField(choices=[('contract', 'Contracts'), ('proposal', 'Proposals'), ('report', 'Reports'), ('letter', 'Letters'), ('invoice', 'Invoices'), ('form', 'Forms'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['author'], name='document_ed_author__30078a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_latest_version'], name='document_ed_is_late_cf7892_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollaborator',
            index=models.Index(fields=['document'], name='document_ed_documen_f08952_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollaborator',
            index=models.Index(fields=['employee'], name='document_ed_employe_7e1e20_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['document'], name='document_ed_documen_991876_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['author'], name='document_ed_author__cb6b61_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcomment',
            index=models.Index(fields=['is_resolved'], name='document_ed_is_reso_587d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['category'], name='document_ed_categor_f9ffc6_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['is_public'], name='document_ed_is_publ_a417a1_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['created_by'], name='document_ed_created_cf7e0e_idx'),
        ),
        migrations.AddField(
            model_name='documenteditsession',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sessions', to='document_editor.document'),
        ),
        migrations.AddField(
            model_name='documenteditsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documenteditsession',
            index=models.Index(fields=['document', 'is_active'], name='document_ed_documen_1f9bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='documenteditsession',
            index=models.Index(fields=['user', 'is_active'], name='document_ed_user_id_f887e9_idx'),
        ),
        migrations.AddIndex(
            model_name='documenteditsession',
            index=models.Index(fields=['last_activity'], name='document_ed_last_ac_84e048_idx'),
        ),
    ]
