# Generated by Django 4.2.18 on 2025-03-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lead_phone'),
        ('document_editor', '0003_alter_document_parent_document_documentversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to='core.employee')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='document_editor.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('department_required', models.CharField(blank=True, choices=[('general', 'General'), ('sales', 'Sales'), ('support', 'Support'), ('engineering', 'Engineering'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('hr', 'Human Resources')], max_length=100)),
                ('position_required', models.CharField(blank=True, choices=[('unassigned', 'Unassigned'), ('junior', 'Junior'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='core.employee')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='document_editor.documentapprovalworkflow')),
            ],
            options={
                'ordering': ['workflow', 'order'],
                'unique_together': {('workflow', 'order')},
            },
        ),
        migrations.CreateModel(
            name='DocumentApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.employee')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='document_editor.documentapprovalstep')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='document_editor.documentapprovalworkflow')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('variable_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes/No'), ('currency', 'Currency'), ('customer', 'Customer Field'), ('project', 'Project Field'), ('employee', 'Employee Field')], max_length=20)),
                ('field_mapping', models.CharField(blank=True, help_text='Field name in the related model', max_length=100)),
                ('default_value', models.CharField(blank=True, help_text='Default value if no value is provided', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the variable for users')),
                ('required', models.BooleanField(default=False)),
                ('date_format', models.CharField(blank=True, help_text="Format string for date variables (e.g., '%Y-%m-%d')", max_length=50)),
                ('number_format', models.CharField(blank=True, help_text="Format string for number variables (e.g., '{:.2f}')", max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='document_editor.documenttemplate')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('template', 'name')},
            },
        ),
    ]
