# Generated by Django 4.2.18 on 2025-04-22 16:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='not_started', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('next_reminder_date', models.DateField(blank=True, null=True)),
                ('send_reminders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboardings', to='core.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('access', 'Access My Data'), ('export', 'Export My Data'), ('correct', 'Correct My Data'), ('delete', 'Delete My Data')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('customer_id', models.CharField(blank=True, help_text='Customer ID if known', max_length=50, null=True)),
                ('details', models.TextField(blank=True, help_text='Additional details to help identify the data')),
                ('verification_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_days', models.PositiveIntegerField(default=7, help_text='Estimated days to complete onboarding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('step_type', models.CharField(choices=[('welcome', 'Welcome'), ('account_setup', 'Account Setup'), ('data_import', 'Data Import'), ('feature_configuration', 'Feature Configuration'), ('team_setup', 'Team Setup'), ('integration', 'Integration Setup'), ('training', 'Training'), ('success_check', 'Success Check')], max_length=30)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(help_text='Order in which step appears')),
                ('is_required', models.BooleanField(default=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=10, help_text='Estimated time to complete in minutes')),
                ('url_name', models.CharField(blank=True, help_text="URL name for this step's view", max_length=100)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('documentation_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='onboarding.onboardingplan')),
            ],
            options={
                'ordering': ['plan', 'order'],
                'unique_together': {('plan', 'order')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingStepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('satisfaction_rating', models.PositiveIntegerField(blank=True, help_text='1-5 satisfaction rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_onboarding_steps', to=settings.AUTH_USER_MODEL)),
                ('customer_onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_completions', to='onboarding.customeronboarding')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='onboarding.onboardingstep')),
            ],
            options={
                'ordering': ['step__order'],
                'unique_together': {('customer_onboarding', 'step')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reminder', 'Reminder'), ('completion', 'Step Completion'), ('milestone', 'Milestone'), ('task', 'Task Assignment'), ('welcome', 'Welcome'), ('plan_change', 'Plan Change')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='onboarding.customeronboarding')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onboarding.onboardingstep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(default='overall', help_text='Type of feedback (overall, step specific, etc.)', max_length=50)),
                ('overall_rating', models.PositiveIntegerField(help_text='1-5 rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ease_of_use_rating', models.PositiveIntegerField(help_text='1-5 rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('support_rating', models.PositiveIntegerField(blank=True, help_text='1-5 rating', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('what_worked_well', models.TextField(blank=True)),
                ('what_could_improve', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('customer_onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='onboarding.customeronboarding')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='onboarding.onboardingstep')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='onboarding.onboardingstep')),
            ],
            options={
                'ordering': ['step', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DataImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('customers', 'Customers'), ('leads', 'Leads'), ('contacts', 'Contacts'), ('products', 'Products/Services'), ('other', 'Other')], max_length=20)),
                ('source_name', models.CharField(help_text='Source system name', max_length=100)),
                ('source_file', models.FileField(upload_to='onboarding/imports/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('records_total', models.PositiveIntegerField(default=0)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_succeeded', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('error_details', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_import_jobs', to=settings.AUTH_USER_MODEL)),
                ('customer_onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='onboarding.customeronboarding')),
                ('related_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='onboarding.onboardingstep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customeronboarding',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_customers', to='onboarding.onboardingstep'),
        ),
        migrations.AddField(
            model_name='customeronboarding',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='core.customer'),
        ),
        migrations.AddField(
            model_name='customeronboarding',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_onboardings', to='onboarding.onboardingplan'),
        ),
        migrations.CreateModel(
            name='ChecklistItemCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='onboarding.onboardingchecklistitem')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('onboarding_step_completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_completions', to='onboarding.onboardingstepcompletion')),
            ],
            options={
                'unique_together': {('onboarding_step_completion', 'checklist_item')},
            },
        ),
    ]
